### ISSUE TITLE
As a user I can search a keyword

### ISSUE THREAD

**Issue by stefangjk** [cs2103aug2015-t16-3j/main#5]
so that I can find something I could not remember.

**Comment by sohjionghao** [comment]
For the date, the user can search a key date in the format in Flex.java, i.e. dd/mm/yyyy

For starting time and ending time, the search term must be a string of 4 digits.

For task title, task description, priority and category, the search term can be a mix of alphabets and digits, or only contain alphabets, or only contain digits.
